/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package week5;

import java.awt.Desktop;
import java.util.*;
import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aashutosh Sinha
 */
public class Coursework extends javax.swing.JFrame {

    /**
     * Creates new form Coursework
     */
    public Coursework() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        Frame2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        Jlabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BusinessButton1 = new javax.swing.JRadioButton();
        EconomyButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DomesticButton = new javax.swing.JRadioButton();
        InternationalButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        CBdestination = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbAirline = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        SortCB = new javax.swing.JComboBox<>();
        ADD = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtcost = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonSearch = new javax.swing.JButton();
        txtfldSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtlname = new javax.swing.JTextField();
        txtticket = new javax.swing.JTextField();
        ADD1 = new javax.swing.JButton();
        jCheckBoxTerm = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        categoryCB = new javax.swing.JComboBox<>();
        btnSearch2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSearch3 = new javax.swing.JButton();
        Year = new javax.swing.JComboBox<>();
        DateMon = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuOpenTxt = new javax.swing.JMenuItem();
        jMenuItemOpenCSV = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Frame2"); // NOI18N

        Frame2.setBackground(new java.awt.Color(204, 204, 255));
        Frame2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "@Powered by  Islington College. Rights reserved ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_BOTTOM, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        Frame2.setAlignmentY(0.9F);

        Table.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer's First Name", "Customer's Last Name", "Ticket Number", "Flight Category", "Flight Class", "Destination", "Deparature Date", "Airline", "Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.setGridColor(new java.awt.Color(153, 0, 51));
        Table.setShowGrid(true);
        Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Table);
        if (Table.getColumnModel().getColumnCount() > 0) {
            Table.getColumnModel().getColumn(0).setResizable(false);
            Table.getColumnModel().getColumn(1).setResizable(false);
            Table.getColumnModel().getColumn(2).setResizable(false);
            Table.getColumnModel().getColumn(3).setResizable(false);
            Table.getColumnModel().getColumn(4).setResizable(false);
            Table.getColumnModel().getColumn(5).setResizable(false);
            Table.getColumnModel().getColumn(6).setResizable(false);
            Table.getColumnModel().getColumn(7).setResizable(false);
            Table.getColumnModel().getColumn(8).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Customer's First Name:");

        txtfname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });

        Jlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jlabel.setText("Customer's Last Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Flight class:");

        BusinessButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(BusinessButton1);
        BusinessButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BusinessButton1.setText("Business");
        BusinessButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusinessButton1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(EconomyButton);
        EconomyButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EconomyButton.setText("Economy");
        EconomyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EconomyButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Ticket Number:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Flight category:");

        DomesticButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(DomesticButton);
        DomesticButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DomesticButton.setForeground(new java.awt.Color(255, 51, 51));
        DomesticButton.setText("Domestic");
        DomesticButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DomesticButtonActionPerformed(evt);
            }
        });

        InternationalButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(InternationalButton);
        InternationalButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        InternationalButton.setForeground(new java.awt.Color(255, 51, 51));
        InternationalButton.setText("International");
        InternationalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InternationalButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Destination:");

        CBdestination.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CBdestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose your Destination" }));
        CBdestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBdestinationActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Choose Airline:");

        cbAirline.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbAirline.setForeground(new java.awt.Color(153, 0, 51));
        cbAirline.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Airline" }));
        cbAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAirlineActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Sort Booking:");

        SortCB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SortCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Sorting", "Acending ", "Decending" }));
        SortCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortCBActionPerformed(evt);
            }
        });

        ADD.setBackground(new java.awt.Color(51, 255, 102));
        ADD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ADD.setText("ADD");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(102, 102, 102));
        delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        delete.setForeground(new java.awt.Color(204, 0, 0));
        delete.setText("DELETE DATA");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Departure Date:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Cost:");

        txtcost.setEditable(false);
        txtcost.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setForeground(new java.awt.Color(102, 0, 51));

        jButtonSearch.setBackground(new java.awt.Color(204, 0, 51));
        jButtonSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSearch.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        txtfldSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtfldSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 51), 3, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSearch)
                .addGap(29, 29, 29)
                .addComponent(txtfldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtfldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonSearch))
        );

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 51));
        jButton1.setText("?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtlname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtticket.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        ADD1.setBackground(new java.awt.Color(204, 204, 204));
        ADD1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ADD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/week5/Back.png"))); // NOI18N
        ADD1.setText("Go Back");
        ADD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD1ActionPerformed(evt);
            }
        });

        jCheckBoxTerm.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jCheckBoxTerm.setText(" I accept all the terms and conditions ");
        jCheckBoxTerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTermActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Sort Airlines:");

        categoryCB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        categoryCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a Category", "Nepal Airlines", "Himalayal Airlines", "Indigo Airlines", "Qatar Airlines", "Buddha Airlines", "Shree Airlines", "Yeti Airlines", "Sita Airlines" }));
        categoryCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryCBActionPerformed(evt);
            }
        });

        btnSearch2.setBackground(new java.awt.Color(102, 102, 102));
        btnSearch2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch2.setForeground(new java.awt.Color(204, 0, 0));
        btnSearch2.setText("SEARCH");
        btnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Calculate cost for Two or more :");

        btnSearch3.setBackground(new java.awt.Color(102, 102, 102));
        btnSearch3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch3.setText("Open Calculator");
        btnSearch3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch3ActionPerformed(evt);
            }
        });

        Year.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022" }));

        DateMon.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        DateMon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));

        month.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC" }));

        javax.swing.GroupLayout Frame2Layout = new javax.swing.GroupLayout(Frame2);
        Frame2.setLayout(Frame2Layout);
        Frame2Layout.setHorizontalGroup(
            Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Frame2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Frame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Frame2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(530, 530, 530)
                        .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Frame2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Frame2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtticket, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Frame2Layout.createSequentialGroup()
                                .addComponent(Jlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Frame2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtcost, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Frame2Layout.createSequentialGroup()
                        .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Frame2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ADD1))
                            .addGroup(Frame2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Frame2Layout.createSequentialGroup()
                                        .addComponent(btnSearch3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Frame2Layout.createSequentialGroup()
                                        .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(Frame2Layout.createSequentialGroup()
                                                    .addComponent(DateMon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(2, 2, 2)
                                                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(4, 4, 4)
                                                    .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(CBdestination, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(Frame2Layout.createSequentialGroup()
                                                            .addComponent(DomesticButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(InternationalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(Frame2Layout.createSequentialGroup()
                                                            .addComponent(BusinessButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(31, 31, 31)
                                                            .addComponent(EconomyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addComponent(categoryCB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SortCB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSearch2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
            .addGroup(Frame2Layout.createSequentialGroup()
                .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Frame2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxTerm)
                            .addComponent(jButton1))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Frame2Layout.setVerticalGroup(
            Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame2Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Frame2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DomesticButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(InternationalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtticket, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Frame2Layout.createSequentialGroup()
                                .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BusinessButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EconomyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Frame2Layout.createSequentialGroup()
                                .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBdestination, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtcost, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Frame2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateMon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Frame2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SortCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoryCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Frame2Layout.createSequentialGroup()
                        .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Frame2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(Frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxTerm)
                        .addGap(13, 13, 13)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Frame2Layout.createSequentialGroup()
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ADD1)))
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 51, 51));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        jMenu1.setText("File");

        jMenuOpenTxt.setText("Open.txt");
        jMenuOpenTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOpenTxtActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuOpenTxt);

        jMenuItemOpenCSV.setText("Open .csv");
        jMenuItemOpenCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenCSVActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemOpenCSV);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Get Help");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Frame2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Frame2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAirlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAirlineActionPerformed

    private void DomesticButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DomesticButtonActionPerformed
        // TODO add your handling code here:
       if(DomesticButton.isSelected())
           CBdestination.removeItem("KTM-Delhi");
           CBdestination.removeItem("KTM-Japan");
           CBdestination.removeItem("KTM-Dubai");
           CBdestination.removeItem("KTM-Oman");
           CBdestination.removeItem("KTM-Berlin");
           CBdestination.removeItem("KTM-Amsterdem");
           CBdestination.removeItem("KTM-Budapest");
           CBdestination.removeItem("KTM-Kola Lampur"); 
           
           CBdestination.addItem("KTM-PKR");
           CBdestination.addItem("KTM-BRT");
           CBdestination.addItem("KTM-JHAPA");
           CBdestination.addItem("KTM-Janakpur");
           
           cbAirline.removeAllItems();
           cbAirline.addItem("Buddha Airlines");
           cbAirline.addItem("Shree Airlines");
           cbAirline.addItem("Yeti Airlines");
           cbAirline.addItem("Sita Airlines");
        


            
            
    }//GEN-LAST:event_DomesticButtonActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
       DefaultTableModel TBLModel = (DefaultTableModel) Table.getModel();
        if(Table.getSelectedRowCount()==1){
            txtfname.setText("");
            txtlname.setText("");
            txtcost.setText("");
            txtticket.setText("");
            TBLModel.removeRow(Table.getSelectedRow());
        }
        else{
            if(Table.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"Table is Empty.");
            }
        else{
            JOptionPane.showMessageDialog(this,"Please Select Single Row For Delete");
        }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        String fName = txtfname.getText();
        String LName = txtlname.getText();
        String TicketNum = txtticket.getText();
        String radio1="";
        String radio2="";
        String selectedvalue = CBdestination.getSelectedItem().toString();
       // String Departuredate = txtdate.getText();
        String Cost = txtcost.getText();
        String air = cbAirline.getSelectedItem().toString();
        String startyear2 = (DateMon.getSelectedItem()).toString();
        String startmonth2 = (month.getSelectedItem()).toString();
        String startday2 = (Year.getSelectedItem()).toString();
        String Departuredate = (startyear2+"-"+startmonth2+"-"+startday2);
       
        if(DomesticButton.isSelected()){
            radio1=DomesticButton.getText().toString();
        }
        if(InternationalButton.isSelected()){
            radio1=InternationalButton.getText().toString();
         
        }
       
         if(BusinessButton1.isSelected()){
            radio2=BusinessButton1.getText().toString();
        }
        if(EconomyButton.isSelected()){
            radio2=EconomyButton.getText().toString();
        }
        
        if(jCheckBoxTerm.isSelected()){
           

        String[] name = {fName, LName, TicketNum,radio1,radio2,selectedvalue, Departuredate,air,Cost};
        int rowCount = Table.getRowCount();
        int columnCount = Table.getColumnCount();
        

        for (String s : name) {
            if (s.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Please dont leave any fields empty");
                return;
            }
        }
      //duplicate data validation
        for (int i = 0; i < rowCount; i++) {
            String thistktnum = (String) Table.getValueAt(i, 2);
            

            if (thistktnum.equals(TicketNum)) {
                JOptionPane.showMessageDialog(rootPane, "Duplicate Ticket Number");
                return;
            }
        }
        
            addEmptyRow();
        
        for (int i = 0; i < Table.getColumnCount(); i++) {
            Table.setValueAt(name[i], rowCount, i);
            
        }
        JOptionPane.showMessageDialog(rootPane, "DATA ADDED SUCCESSFULLY!");

        }
        else{
            JOptionPane.showMessageDialog(this, "Please accept all the terms and conditions.", "Message", JOptionPane.ERROR_MESSAGE);
        }

 
         
    }//GEN-LAST:event_ADDActionPerformed
public void addEmptyRow() {
        DefaultTableModel tableModel = (DefaultTableModel) Table.getModel();
         tableModel.addRow(new Object[]{null});
}
    
    private void jMenuOpenTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOpenTxtActionPerformed
        // TODO add your handling code here:
        JFileChooser j = new JFileChooser();
        int response =j.showSaveDialog(null);
        
        System.out.println(response);   
            
            try {
                if (response == JFileChooser.APPROVE_OPTION) {
            File file = new File(j.getSelectedFile().getAbsolutePath());
            
                BufferedReader BR= new BufferedReader(new FileReader(file));
                String firstLine = BR.readLine().trim();
                String [] columnsName = firstLine.split(",");
                DefaultTableModel model = (DefaultTableModel)Table.getModel();
                model.setColumnIdentifiers(columnsName);
                Object[] tableLines = BR.lines().toArray();
                
                for (int i = 0; i < tableLines.length; i++) {
                    String line = tableLines[i].toString().trim();
                    String [] dataRow = line.split("/");
                    model.addRow(dataRow);
                    
                
                }
                    
                }
                
                
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Coursework.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Coursework.class.getName()).log(Level.SEVERE, null, ex);
            }

    
        
    }//GEN-LAST:event_jMenuOpenTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane,"Airline Information system is a Java based software which is \n"
                + "developed by a group of three students named Subarna Karki, Aasutosh Kumar Singh and Kishor Katuwal.\n"
                + "It's a piece of software that allows you to book domestic and international flights through the internet.\n"
                + "Users can fill in their basic information, select their locations and select their, \n"
                + "airlines,with the added bonus that the cost of the airline based on their destination"
                + "is calculated and added to the table directly. ","Information", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void ADD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD1ActionPerformed
        // TODO add your handling code here:
    CollegeIS goback =  new CollegeIS();
        goback.setVisible(true);    
        
    }//GEN-LAST:event_ADD1ActionPerformed

    private void CBdestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBdestinationActionPerformed
        // TODO add your handling code here:          
            if(DomesticButton.isSelected()==true){    
            cbAirline.removeAllItems();
            cbAirline.addItem("Buddha Airlines");
            cbAirline.addItem("Shree Airlines");
            cbAirline.addItem("Yeti Airlines");
            cbAirline.addItem("Sita Airlines");

                
                if(CBdestination.getSelectedItem().toString()=="KTM-PKR"){
                txtcost.setText("2500");
            }
            else if(CBdestination.getSelectedItem()=="KTM-BRT"){
                txtcost.setText("3500");
            }
             else if(CBdestination.getSelectedItem().toString()=="KTM-Janakpur"){
                txtcost.setText("2000");
            }
             else  if(CBdestination.getSelectedItem().toString()=="KTM-JHAPA"){
                txtcost.setText("4000");
            }
                else{
                     txtcost.setText("");
                 }
            }
            else if(InternationalButton.isSelected()==true){
               
 
  
            cbAirline.removeAllItems();
            cbAirline.addItem("Nepal Airlines");
            cbAirline.addItem("Himalayal Airlines");
            cbAirline.addItem("Indigo Airlines");
            cbAirline.addItem("Qatar Airlines");
                
                
                if(CBdestination.getSelectedItem().toString()=="KTM-Delhi"){
                txtcost.setText("30000");
            }
                else if(CBdestination.getSelectedItem().toString()=="KTM-Japan"){
                txtcost.setText("75000");
            }
                else  if(CBdestination.getSelectedItem().toString()=="KTM-Dubai"){
                txtcost.setText("60000");
            }
                 else  if(CBdestination.getSelectedItem().toString()=="KTM-DOHA"){
                txtcost.setText("80000");
            } 
              else  if(CBdestination.getSelectedItem().toString()=="KTM-Oman"){    
                txtcost.setText("90000");
            }
            else  if(CBdestination.getSelectedItem().toString()=="KTM-Berlin"){
                txtcost.setText("100000");
            }
            else  if(CBdestination.getSelectedItem().toString()=="KTM-Amsterdem"){
                txtcost.setText("120000");
            }
            else  if(CBdestination.getSelectedItem().toString()=="KTM-Budapest"){
                txtcost.setText("140000");
            }
            else  if(CBdestination.getSelectedItem().toString()=="KTM-Kola Lampur"){
                txtcost.setText("105000");
            }
                 else{
                     txtcost.setText("");
                 }
            }

        
        
        
        
    }//GEN-LAST:event_CBdestinationActionPerformed

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        
        ArrayList<String> fname = new ArrayList();
        ArrayList<String>  lname = new ArrayList();
        ArrayList<String> fcategory = new ArrayList();
        ArrayList<String> destination = new ArrayList();
        ArrayList<String> date = new ArrayList();
        ArrayList<String> airline = new ArrayList();
        ArrayList<Integer> cost= new ArrayList();
        ArrayList<String> tktnum= new ArrayList();
        ArrayList<String>  fclass = new ArrayList();
         
        int rowCount = Table.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            String sfname = (String) Table.getValueAt(i, 0);
            String slname = (String) Table.getValueAt(i, 1);
            String stktnum = (String) Table.getValueAt(i, 2);
            String sfcategory = (String) Table.getValueAt(i, 3);
            String sfclass = (String) Table.getValueAt(i, 4);
            String sdestination = (String) Table.getValueAt(i, 5);
            String sddate = (String) Table.getValueAt(i, 6);
            String sairline = (String) Table.getValueAt(i, 7);
            String scost = (String) Table.getValueAt(i, 8);
            

            if(sfname != null && slname != null && stktnum!=null &&sfcategory!=null &&sfclass!=null &&
                    sdestination != null && sddate != null && sairline!=null &&scost!=null ){
                
                fname.add(sfname);
                lname.add(slname);
                tktnum.add(stktnum);
                fcategory.add(sfcategory);
                fclass.add(sfclass);
                destination.add(sdestination);
                date.add(sddate);
                airline.add(sairline);
                cost.add(Integer.parseInt(scost));
                
            }
        }
        
            for (int i = 0; i < cost.size(); i++) {
            int min = i;
            for (int j = i + 1; j < cost.size(); j++) {
               
                    if (cost.get(j) < cost.get(min)) {
                        min = j;
                    }
                }
            
            // swapping array values
            int costTemp = cost.get(min);
            cost.set(min, cost.get(i));
            cost.set(i, costTemp);

            String fnameTemp = fname.get(min);
            fname.set(min, fname.get(i));
            fname.set(i, fnameTemp);

            String  lnameTemp = lname.get(min);
            lname.set(min, lname.get(i));
            lname.set(i, lnameTemp);
            
            String tktTemp = tktnum.get(min);
            tktnum.set(min, tktnum.get(i));
            tktnum.set(i, tktTemp);
            
            String categoryTemp = fcategory.get(min);
            fcategory.set(min, fcategory.get(i));
            fcategory.set(i, categoryTemp);
            
            String classTemp = fclass.get(min);
            fclass.set(min, fclass.get(i));
            fclass.set(i, classTemp);

            String  destinationTemp = destination.get(min);
            destination.set(min, destination.get(i));
            destination.set(i, destinationTemp);
            
            String dateTemp = date.get(min);
            date.set(min, date.get(i));
            date.set(i, dateTemp);
            
            String airlineTemp = airline.get(min);
            airline.set(min, airline.get(i));
            airline.set(i, airlineTemp);
            }
          
    try{
        int val = Integer.parseInt(txtfldSearch.getText());
        int low = 0;
        int high = cost.size();
        int output = binarySearch(cost, low, high, val);
        
        if(output == -1 ){
            
            JOptionPane.showMessageDialog(this, "Value not Found: " , "Message", JOptionPane.ERROR_MESSAGE);
           
        }
        else{
            int getCost = cost.get(output);
            String getFname = fname.get(output);
            String getLname = lname.get(output);
            String getTicket = tktnum.get(output);
            String getCategory = fcategory.get(output);
            String getClass = fclass.get(output);
            String getDestination = destination.get(output);
            String getDate = date.get(output);
            String getAirline= airline.get(output);
            
                 JOptionPane.showMessageDialog(this,"THE DETAILS ARE AS FOLLOWS:-\n" +
                         "The full name of the customer is "+ getFname +" "+getLname +".\n"+
                         getAirline+ " is the selected airline and " + getDestination+ " is the destination.\n"+
                         "The ticket number is " +getTicket+"and the cost of the ticket is "+getCost+".\n",
                         "Message" , JOptionPane.INFORMATION_MESSAGE);
        }
        
    }
    catch(Exception e){
             JOptionPane.showMessageDialog(this, "Insert integer value \n"
                     + "OR Cost out of bounds" , "Message", JOptionPane.ERROR_MESSAGE);
    }
        
        

    }//GEN-LAST:event_jButtonSearchActionPerformed

    public int binarySearch(ArrayList<Integer> a, int lower, int higher, int value){
        int mid = (lower+higher)/2;
        if(lower>higher){
            return -1;
        }
        if(a.get(mid) == value){
            return mid;
        }else if(value<a.get(mid)){
            return binarySearch(a, lower, mid-1, value);
        }else{
            return binarySearch(a, mid+1, higher, value);
        }
    }

        public void sort(int order) {
      
        int count = 0;
       for (int x = 0; x < Table.getRowCount(); x++){
           if (Table.getValueAt(x,0) != null){
               count++;
           }
       }
     
        Object[] a = new Object[count];
         
        int rowCount = Table.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            String cost = (String) Table.getValueAt(i,8);
            if (cost != null) {
                a[i] = cost;
            }
        }
        for (int i = 0; i < a.length; i++) {
            int min = i;
            for (int j = i + 1; j < a.length; j++) {
              
                if (order == 0) {
                    if (a[j].toString().compareTo(a[min].toString())<0) {
                        min = j;
                    }
                } else if (order == 1){
                    if (a[j].toString().compareTo(a[min].toString())>0) {
                        min = j;
                    }
                }
            }
            
            // swapping array values.
            Object temp = a[min];
            a[min] = a[i];
            a[i] = temp;
            
           String fnameTemp = (String) Table.getValueAt(i, 0);
            Table.setValueAt(Table.getValueAt(min, 0), i, 0);
            Table.setValueAt(fnameTemp, min, 0);

            
            String lnameTemp = (String) Table.getValueAt(i, 1);
            Table.setValueAt(Table.getValueAt(min, 1), i, 1);
            Table.setValueAt(lnameTemp, min, 1);

            
            String tktTemp = (String) Table.getValueAt(i, 2);
            Table.setValueAt(Table.getValueAt(min, 2), i, 2);
            Table.setValueAt(tktTemp, min, 2);
            
            String categoryTemp = (String) Table.getValueAt(i, 3);
            Table.setValueAt(Table.getValueAt(min, 3), i, 3);
            Table.setValueAt(categoryTemp, min, 3);
            
            
            String classTemp = (String) Table.getValueAt(i, 4);
            Table.setValueAt(Table.getValueAt(min, 4), i, 4);
            Table.setValueAt(classTemp, min, 4);
            
            String destinationTemp = (String) Table.getValueAt(i, 5);
            Table.setValueAt(Table.getValueAt(min, 5), i, 5);
            Table.setValueAt(destinationTemp, min, 5);

           
            String dateTemp = (String) Table.getValueAt(i, 6);
            Table.setValueAt(Table.getValueAt(min, 6), i, 6);
            Table.setValueAt(dateTemp, min, 6);
            
            String airlineTemp = (String) Table.getValueAt(i, 7);
            Table.setValueAt(Table.getValueAt(min, 7), i, 7);
            Table.setValueAt(airlineTemp, min, 7);
            
            
            String costTemp = (String) Table.getValueAt(i, 8);
            Table.setValueAt(Table.getValueAt(min, 8), i, 8);
            Table.setValueAt(costTemp, min, 8);
        }
    }
        
        
    
    private void jCheckBoxTermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTermActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jCheckBoxTermActionPerformed

    private void InternationalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InternationalButtonActionPerformed
        // TODO add your handling code here:
        CBdestination.removeItem("KTM-PKR");
        CBdestination.removeItem("KTM-BRT");
        CBdestination.removeItem("KTM-JHAPA");
        CBdestination.removeItem("KTM-Janakpur");     
               
               
        CBdestination.addItem("KTM-Delhi");
        CBdestination.addItem("KTM-Japan");
        CBdestination.addItem("KTM-Dubai");
        CBdestination.addItem("KTM-Oman");
        CBdestination.addItem("KTM-Berlin");
        CBdestination.addItem("KTM-Amsterdem");
        CBdestination.addItem("KTM-Budapest");
        CBdestination.addItem("KTM-Kola Lampur");
                
               
        cbAirline.removeAllItems();
        cbAirline.addItem("Nepal_Airlines");
        cbAirline.addItem("Himalayal Airlines");
        cbAirline.addItem("Indigo Airlines");
        cbAirline.addItem("Qatar Airlines");
           
               
        
        
    }//GEN-LAST:event_InternationalButtonActionPerformed

    private void SortCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortCBActionPerformed
        // TODO add your handling code here:
        
        int selected = SortCB.getSelectedIndex();
        if (selected == 0) {

            System.out.println("Select a value");
        } else if (selected == 1) {
            sort(0);
        } else if(selected == 2){
            sort(1);
            
        }
    }//GEN-LAST:event_SortCBActionPerformed

    private void categoryCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryCBActionPerformed

    private void btnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch2ActionPerformed

        
     //   String kk = categoryCB.getSelectedItem().toString();
   
            String category = categoryCB.getSelectedItem().toString();

            if(category==("Choose a Category")){
                JOptionPane.showMessageDialog(this, "Please Choose a Category" , "Message", JOptionPane.INFORMATION_MESSAGE);
            }
            else{

            int categoryIndex = 7;
            int rows = Table.getRowCount();
            int no = 1;
            String fName="";
            String lName="";
            String Name="";
            for (int i = 0; i < rows; i++) 
            {
            if ((Table.getValueAt(i, categoryIndex).toString()).equals(category))
            { 
            //searchIndex1 is assigned with 1 since our category is at 1st position of the array.

            fName = ((String) Table.getValueAt(i, 0)) ;
            lName = ((String) Table.getValueAt(i, 1))+"\n" ;
             Name=Name + no+"."+ fName +" "+ lName;

            no++;

            }

            }

            if (!"".equals(fName))
            {
           JOptionPane.showMessageDialog(this, Name, (no-1) + " People  from  " + category+" category.", JOptionPane.INFORMATION_MESSAGE);

            } 
            else 
            {

            JOptionPane.showMessageDialog(this, "No People Related to Category: " + category, "Message", JOptionPane.INFORMATION_MESSAGE);

            } 


            }

        
        

    }//GEN-LAST:event_btnSearch2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnSearch3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch3ActionPerformed
        // TODO add your handling code here:
      setVisible(false);
        new calculator().setVisible(true);   
    }//GEN-LAST:event_btnSearch3ActionPerformed

    private void BusinessButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusinessButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BusinessButton1ActionPerformed

    private void EconomyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EconomyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EconomyButtonActionPerformed

    private void jMenuItemOpenCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenCSVActionPerformed
        // TODO add your handling code here:
    String file = "C:\\Users\\Aashutosh Sinha\\Downloads\\Test.xlsx";
     BufferedReader reader = null;
     String line = "";

     try {
      reader = new BufferedReader(new FileReader(file));
      while((line = reader.readLine()) != null) {

       String[] row = line.split(",");

       for(String index : row) {
        System.out.printf("%-10s", index);
       }
       System.out.println();
      }
     }
     catch(Exception e) {
      e.printStackTrace();
     }
     finally {
      try {
       reader.close();
      } catch (IOException e) {
       // TODO Auto-generated catch block
       e.printStackTrace();
      }
     }
    
    }//GEN-LAST:event_jMenuItemOpenCSVActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coursework.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coursework.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coursework.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coursework.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coursework().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JButton ADD1;
    private javax.swing.JRadioButton BusinessButton1;
    private javax.swing.JComboBox<String> CBdestination;
    private javax.swing.JComboBox<String> DateMon;
    private javax.swing.JRadioButton DomesticButton;
    private javax.swing.JRadioButton EconomyButton;
    private javax.swing.JPanel Frame2;
    private javax.swing.JRadioButton InternationalButton;
    private javax.swing.JLabel Jlabel;
    private javax.swing.JComboBox<String> SortCB;
    private javax.swing.JTable Table;
    private javax.swing.JComboBox<String> Year;
    private javax.swing.JButton btnSearch2;
    private javax.swing.JButton btnSearch3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> categoryCB;
    private javax.swing.JComboBox<String> cbAirline;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JCheckBox jCheckBoxTerm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemOpenCSV;
    private javax.swing.JMenuItem jMenuOpenTxt;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField txtcost;
    private javax.swing.JTextField txtfldSearch;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtticket;
    // End of variables declaration//GEN-END:variables

    private void close() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
